// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYhAxvI5b8KtFgLQoa1uicr1rAQBT7ch4',
    appId: '1:891202497994:web:38c9f975e9ce42c6ad3333',
    messagingSenderId: '891202497994',
    projectId: 'online-learning-app-13edf',
    authDomain: 'online-learning-app-13edf.firebaseapp.com',
    storageBucket: 'online-learning-app-13edf.appspot.com',
    measurementId: 'G-F158PQKS4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfe8_13P1vRq-RzS-N1ZGU5YGE789Lpa0',
    appId: '1:891202497994:android:b35fdbb5129eead2ad3333',
    messagingSenderId: '891202497994',
    projectId: 'online-learning-app-13edf',
    storageBucket: 'online-learning-app-13edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNpyv5iMErTKD-4mM4_M2yIV8jmWQdvI',
    appId: '1:891202497994:ios:fae156a7305c6617ad3333',
    messagingSenderId: '891202497994',
    projectId: 'online-learning-app-13edf',
    storageBucket: 'online-learning-app-13edf.appspot.com',
    iosBundleId: 'com.example.onlineLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNpyv5iMErTKD-4mM4_M2yIV8jmWQdvI',
    appId: '1:891202497994:ios:9d755b7e80eb42e3ad3333',
    messagingSenderId: '891202497994',
    projectId: 'online-learning-app-13edf',
    storageBucket: 'online-learning-app-13edf.appspot.com',
    iosBundleId: 'com.example.onlineLearningApp.RunnerTests',
  );
}
